### ISSUE TITLE
Could not import Open API spec v2.0

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/swagger2-postman2#34]
**Describe the bug**
This OAS v2.0 will not import into Postman v7.2.2 (either from a file or from a link). However the import previously worked on Postman v6.7.4.

**To Reproduce**
### Importing as link
1. Import this OAS v2.0 link: https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.15/api/openapi-spec/swagger.json
2. See error: Swagger 2.0: Could not import
### Importing as file
1. Download and save as a file, and then import this OAS v2.0 file: https://github.com/kubernetes/kubernetes/blob/release-1.15/api/openapi-spec/swagger.json
2. See error: Swagger 2.0: Could not import

**Screenshots**
<img width="1461" alt="Screen Shot 2019-07-01 at 4 54 56 PM" src="https://user-images.githubusercontent.com/17693714/60473223-039d3900-9c21-11e9-9712-53f008a14e7f.png">

**App information (please complete the following information):**
macOS v7.2.2

**Comment by dujfalusi** [comment]
Same issue

**Comment by coand** [comment]
Same issue for me in macOS using version 7.2.2. Worked before this release.

**Comment by TrentonAdams** [comment]
Same issue for me, I used the direct url to my kubernetes server...
http://127.0.0.1:32769/openapi/v2

**Comment by DominikFG** [comment]
Same issue in v7.5.0

**Comment by coand** [comment]
I used PostmanCanary Version 7.7.0-canary02 to import an Open API spec v2.0 yaml file and it was successful. The same yaml file failed to import with Postman 7.6.

**Comment by coand** [comment]
confirmed this is resolved in the released version of Postman 7.7.

**Comment by rob4629** [comment]
👋 Hi, can this issue be re-opened? I'm using v7.16, and still getting the same error. I've looked at different possible causes:
1. Change "swagger": "2.0" to "openapi"
2. Add "openapi": "3.0" to my json file
3. Remove any `?` from api urls (there are no query urls in my file)
4. Copy the text and import directly as RAW json

No luck, still getting the same unhelpful error message.

**Comment by Gausee** [comment]
Any Update on this issue, we are doing a POC on contract test using Postman and were not able to import OAS 2.0 docs, is this in scope to be fixed for all current and later releases?
